spring:
  application:
    name: acougue-erp
  datasource:
    url: jdbc:h2:mem:acougue_erp
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    com.acougue.erp: DEBUG
    org.hibernate.SQL: DEBUG

# ⚠️ CONFIGURAÇÃO DAS BALANÇAS - ADICIONE APENAS ESTA SEÇÃO 'app'
app:
  balanca:
    filizola:
      porta: COM3
      baud-rate: 9600
    toledo:
      porta: COM4
      baud-rate: 9600
  precificacao:
    margem-lucro-padrao: 30.0